name: "Sync Tailscale ACLs"

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      tailnet:
        description: "Tailnet name (eg. example.com, xe.github, tailscale.org.github)"
        required: true
      api-key:
        description: "Tailscale API key"
        required: true
      policy-file:
        description: "Path to policy file"
        required: true
        default: ./policy.hujson
      action:
        description: "Action to take (test/apply)"
        required: true

jobs:
  sync-acls:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker
        run: docker --version

      - name: Build Docker image
        run: docker build -t my-tailscale-image .

      - name: Run Docker container
        run: |
          docker run \
            -e TS_API_KEY=${{ github.event.inputs.api-key }} \
            -e TS_TAILNET=${{ github.event.inputs.tailnet }} \
            my-tailscale-image \
            --policy-file=${{ github.event.inputs.policy-file }} \
            ${{ github.event.inputs.action }}
