name: "Sync Tailscale ACLs"

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      tailnet:
        description: "Tailnet name (eg. example.com, xe.github, tailscale.org.github)"
        required: true
      api-key:
        description: "Tailscale API key"
        required: true
      policy-file:
        description: "Path to policy file"
        required: true
        default: ./policy.hujson
      action:
        description: "Action to take (test/apply)"
        required: true

jobs:
  sync-acls:
    runs-on: ubuntu-latest
    env:
      TS_API_KEY: ${{ github.event.inputs.api-key || 'default_API_key' }}
      TS_TAILNET: ${{ github.event.inputs.tailnet || 'default_tailnet' }}
      POLICY_FILE: ${{ github.event.inputs.policy-file || './policy.hujson' }}
      ACTION: ${{ github.event.inputs.action || 'default_action' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker
        run: docker --version

      - name: Build Docker image
        run: docker build -t my-tailscale-image .

      - name: Run Docker container
        run: |
          docker run \
            -e TS_API_KEY=${TS_API_KEY} \
            -e TS_TAILNET=${TS_TAILNET} \
            my-tailscale-image \
            --policy-file=${POLICY_FILE} \
            ${ACTION}
